version: '3.8'
services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - .:/app
    # command удален, чтобы использовался CMD из Dockerfile (start.sh)
